### ISSUE TITLE
Lava ocean ruins/structures only spawning with support pillars

### ISSUE THREAD

**Issue by Cervator** [Terasology/Inferno#3]
Ended up re-testing Inferno (and remembering how cool the transition is) and by chance noticed the little ruined structures meant to spawn in the lava oceans have been reduced to pillars-  which doesn't seem quite right. Not sure how that happened or how long ago. Example screenie: 

![2017-08-05 02_18_13-terasology _ alpha](https://user-images.githubusercontent.com/1063833/28993448-72dc16ea-7984-11e7-91e7-1f1d461abb76.png)

@iojw ping! :-) Also noticed there's a tiny PR pending: #2

**Comment by iojw** [comment]
This was due to the removal of some of the blocks used in the lava huts from the ChiselBlocks module. The module was unable to locate the blocks and thus the lava huts were improperly generated.

Fixed in 953d796e6ee0d75c6d30de504f851ec8b6ac062d.
